version: '3'

services:
  php-apache:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    links:
      - mariadb
    networks:
      - default
    ports:
    - "8080:80"

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

volumes:
  mariadb-data: